[build]
  publish = "dist"
  command = "npm cache clean --force && npm install @progress/kendo-react-common@7.0.2 --save-exact && npm install --legacy-peer-deps --force && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 